# Development Environment Values for Conduit Matrix Server
# This file extends the base values.yaml with dev-specific overrides

# Development-friendly server configuration
config:
  server_name: "conduit.local"
  allow_registration: true
  allow_federation: false
  allow_encryption: true
  log: "debug,rocket=info,_=off,sled=off"  # More verbose logging for dev

# Nginx configuration for development
nginx:
  enabled: true
  serverName: "conduit.local"
  service:
    type: LoadBalancer  # Use LoadBalancer for easy local access
    port: 8443
  tls:
    secretName: "conduit-tls"

# Smaller resource requirements for local development
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Smaller storage for dev
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: "hostpath"  # Use the default hostpath storage class

# User setup enabled with test users
userSetup:
  enabled: true
  createTestRoom: true
  users:
    - username: "admin"
      password: "admin123"
      displayName: "Administrator"
      isAdmin: true
    - username: "bob"
      password: "bob123"
      displayName: "Bob Smith"
      isAdmin: false
    - username: "rachel"
      password: "rachel123"
      displayName: "Rachel Green"
      isAdmin: false
    - username: "alice"
      password: "alice123"
      displayName: "Alice Wonder"
      isAdmin: false
    - username: "charlie"
      password: "charlie123"
      displayName: "Charlie Brown"
      isAdmin: false

# Enable ingress for HTTPS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: "conduit.local"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "conduit.local"
      secretName: conduit-tls

# Development annotations
podAnnotations:
  environment: "development" 